#!/bin/sh
# Copyright contributors to Hyperledger Avalon
# SPDX-License-Identifier: Apache-2.0
docker run \
    --rm \
    -e http_proxy \
    -e https_proxy \
    --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
    -v $(pwd):/project/dancap\
    -it dancap-verifier-env /bin/bash \
    -c 'cd /project/dancap; exec "${SHELL:-sh}"' 
