#!/bin/sh
docker run \
    --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
    -v $(pwd):/project/dancap\
    -it dancap-dev-env /bin/bash \
    -c 'cd /project/dancap; exec "${SHELL:-sh}"' 
